### ISSUE TITLE
classify_files with a gpus argument throws an exception.

### ISSUE THREAD

**Issue by ryanhausen** [morpheus-project/morpheus#13]
```
Traceback (most recent call last):
  File "main.py", line 43, in <module>
    main()
  File "main.py", line 40, in main
    Classifier.classify_files(h=h, j=j, v=v, z=z, out_dir='./output/5', gpus=[0,1,2,3,4,5,6,7,8])
  File "/usr/local/lib/python3.6/dist-packages/morpheus/classifier.py", line 216, in classify_files
    Classifier._run_parallel_jobs(gpus, out_dir, parallel_check_interval)
  File "/usr/local/lib/python3.6/dist-packages/morpheus/classifier.py", line 641, in _run_parallel_jobs
    sub_dir = os.path.join(out_dir, gpu)
  File "/usr/lib/python3.6/posixpath.py", line 94, in join
    genericpath._check_arg_types('join', a, *p)
  File "/usr/lib/python3.6/genericpath.py", line 149, in _check_arg_types
    (funcname, s.__class__.__name__)) from None
TypeError: join() argument must be str or bytes, not 'int'
```

**Comment by ryanhausen** [comment]
Still issue:

```
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    from inference import Classifier
ModuleNotFoundError: No module named 'inference'
```

**Comment by ryanhausen** [comment]
Most have this has been fixed in the most recent update, but there is still a bug where a parallel classification isn't finished and recombined into a single image.
